server:
  port: 80

eureka:
  #集群中使用hostname
  instance:
    hostname: order80
    ##服务器注册的Instances 列表的status中使用该名称
    instance-id: order80
    prefer-ip-address: true
   # lease-expiration-duration-in-seconds: 2
    #lease-renewal-interval-in-seconds: 1
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    ##表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    #默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    service-url:
      ##单机
      #defaultZone: http://localhost:7001/eureka
      ##集群
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka


spring:
  application:
    ##必须指定名称，在Eureka server的Instances列表中使用
    name: cloud-order-service
