server:
  port: 8802
spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:                                      #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: admin
                password: admin
                virtual-host: /
      bindings:
        input:                                              #生产者绑定，这个是消息通道的名称
          group: group-A                                    #该项目节点为消息组group-A的一个消费端
          destination: exchange-msgSender                   #exchange名称,交换模式默认是topic;把SpringCloud stream的消息输入通道绑定到RabbitMQ的exchange-msgSender交换器。
          content-type: application/json
          consumer:
            partitioned: true                               #true 表示启用消息分区功能
      instance-count: 2                                     #表示消息分区的消费端节点数量为2个
      instance-index: 0                                     #该参数设置消费端实例的索引号，索引号从0开始。