server:
  port: 7002
spring:
  application:
    #eurekaserver集群的spring.application.name必须要一致
    name: eureka
eureka:
  instance:
    hostname: eureka7002.com
    prefer-ip-address: true
  client:
    ##表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    ##表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    service-url:
      ###单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      ##集群版
      defaultZone: http://eureka7001.com:7001/eureka
#  server:
#    #是否开启自我保护模式，默认为true。
#    #server在15分钟内，renews 和renews threshold 的比值小于指定值(默认值为0.85)进入自我保护状态
#    enable-self-preservation: true
#    eviction-interval-timer-in-ms: 90000
#    renewal-percent-threshold: 0.85


##官网 https://docs.spring.io/spring-cloud-netflix/docs/2.2.5.RELEASE/reference/html/#spring-cloud-eureka-server
##eureka.server.renewalPercentThreshold，定义了renews 和renews threshold的比值，默认值为0.85。当server在15分钟内，
##比值低于percent，即少了15%的微服务心跳，server会进入自我保护状态，Self-Preservation。在此状态下，server不会删除注册信息，
##这就有可能导致在调用微服务时，实际上服务并不存在。
##eureka.server.enableSelfPreservation=false,关闭自我保护

#server:
#  port: 7001
#spring:
#  profiles: 7001
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    #Indicates how often(in seconds) to fetch the registry information from the eureka server.
#    registry-fetch-interval-seconds: 30
#    #Indicates how often(in seconds) to replicate instance changes to be replicated to the eureka server.
#    instance-info-replication-interval-seconds: 30
#  server:
#    #是否开启自我保护模式，默认为true。
#    enable-self-preservation: true
#    eviction-interval-timer-in-ms: 60000
#
#---
#server:
#  port: 7002
#spring:
#  profiles: 7002
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/